jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup VPS
        run: |
          sudo apt update && sudo apt install -y openssh-server
          sudo systemctl start ssh
          sudo systemctl enable ssh
          
          # ✅ Port 22 Allow Karo
          sudo ufw allow 22
          sudo iptables -I INPUT -p tcp --dport 22 -j ACCEPT
          
          # ✅ Check Karo Ki SSH Running Hai
          sudo systemctl restart ssh
          sudo systemctl status ssh
          
          # ✅ Public IP Show Karo
          echo "GitHub VPS IP: $(curl ifconfig.me)"
