name: Free GitHub VPS

on:  
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup VPS
        run: |
          sudo apt update && sudo apt install -y openssh-server
          sudo systemctl start ssh
          sudo systemctl enable ssh
          
          # ✅ Port 22 Allow Karo
          sudo ufw allow 22
          sudo iptables -I INPUT -p tcp --dport 22 -j ACCEPT
          
          # ✅ SSH Configuration Set Karo
          echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
          echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
          echo "root:githubvps" | sudo chpasswd
          
          # ✅ Restart SSH
          sudo systemctl restart ssh

          # ✅ Show Public IP
          echo "GitHub VPS IP: $(curl ifconfig.me)"
          
          # ✅ 6 Hours Tak VPS Band Mat Hone Do
          echo "Keeping VPS alive for 6 hours..."
          while true; do sleep 3600; echo "Still Running..."; done
